services:
  ollama:
    image: ollama/ollama
    container_name: ollama-container
    restart: always
    volumes:
      - ./ollama_entrypoint.sh:/usr/local/bin/ollama_entrypoint.sh
    entrypoint: [ "/usr/bin/bash", "/usr/local/bin/ollama_entrypoint.sh" ]

  server:
    container_name: fastapi-container
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - ollama
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/chat/api/health" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
    volumes:
      - ./server:/server

  client:
    container_name: nuxt-container
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - API_BASE_URL=/chat/api
    volumes:
      - ./client:/client
      - /client/node_modules
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
      - ollama
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
      - client
